version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # 修正したボリュームマウント
      - web-images:/app/static/img  # アプリケーションの画像の永続化
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      SECRET_KEY: 'flask_app_113333555555'
      UPLOAD_FOLDER: '/app/static/img'
      FILE_PATH: 'img'

  db:
    build: ./mysql  # MySQLカスタムDockerfileへのパスを指定
    environment:
      MYSQL_ROOT_PASSWORD: root4645(gmgJ)
      MYSQL_DATABASE: flask_app
      MYSQL_USER: user21
      MYSQL_PASSWORD: user21(PASS)
    volumes:
      - db-data:/var/lib/mysql  # MySQLデータの永続化
      - ./mysql/db:/docker-entrypoint-initdb.d
    ports:
      - "3307:3307"

volumes:
  web-images:  # webサービスの画像用ボリューム
  db-data:     # dbサービスのMySQLデータ用ボリューム
