CREATE TABLE POST_USER (
  post_user_id INT NOT NULL AUTO_INCREMENT COMMENT '投稿ユーザーID',
  post_id INT NOT NULL COMMENT '投稿ID',
  user_id INT NOT NULL COMMENT 'ユーザーID',
  delete_flag CHAR DEFAULT '0' NOT NULL COMMENT '削除フラグ',
  CONSTRAINT POST_USER_PKC PRIMARY KEY (post_user_id)
) CHARACTER SET utf8mb4;
